@echo off
title a i see you
color c 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
echo One hour left 
pause 
